### PR TITLE
Make ansible container sctl capable.

### PR DESCRIPTION
**Pull request by hisham-vaporio**

### CODE REVIEW

**Review by KylerBurke — APPROVED** [review]
Looks sane enough 👍 I somewhat recall a pattern of re-declaring the `WORKDIR` away from /tmp after an install like this. It's been a long time, and that might not apply here, but you might want to test this image using whatever working consumer pattern exists. My concern is that this might break any `entrypoint` or `command` used in compose or charts consumers. Might be worth verifying

**Comment by hisham-vaporio** [comment]
Good and valid points. I'll double check and validate the runs. Thank you.

**Comment by hisham-vaporio** [comment]
I did a check and the dir was set as homedir which was /root. So I ensured it goes back to that.

The command and entrypoint isn't affected by this change based on my test runs.

**Comment by hisham-vaporio** [comment]
Correction: Workdir should be '/' not '/root'. root folder vs root user's home-dir.

**Pull request merged**
